[package]
name = "minitt"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
either = "1.13.0"
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }